service: default
runtime: go
api_version: go1

nobuild_files: src/vendor

handlers:
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico

  - url: /static
    static_dir: static
    application_readable: true

  - url: /
    static_files: static/index.html
    upload: static/index.html
    application_readable: true

  - url: /dashboard/.*
    script: _go_app
    login: admin

